<Principal>:
    id: HomeScreen
    FloatLayout:
        Button:
            text:'BUTTON'
            on_release: root.Btnmic()
            size_hint: (.3,.1)
            color: 145/255, 164/255, 130/255
            pos_hint: {'x':.35, 'y':.3}
        TextInput:
            id: lblMessage
            color: 0, 0, 0
            text: 'hello'
            size_hint: (.6,.2)
            pos_hint: {'x':.2, 'y':.6}